apiVersion: apps/v1
kind: Deployment
metadata:
  name: oradb
  namespace: spark-lab8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oradb
  template:
    metadata:
      name: oradb
      labels:
        app: oradb
    spec:
      containers:
        - name: oradb
          image: container-registry.oracle.com/database/free:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 2Gi
            limits:
              memory: 2Gi
          ports:
            - containerPort: 1521
              hostPort: 1521
          env:
            - name: ORACLE_PWD
              value: "12345"

---
apiVersion: v1
kind: Service
metadata:
  name: oradb
  namespace: spark-lab8
spec:
  selector:
    app: oradb
  ports:
  - protocol: TCP
    port: 1521
    targetPort: 1521